baseurl = "http://localhost:1313/"
title = "Bonnie Luo"
languageCode = "en-us"
preserveTaxonomyNames = true
hasCJKLanguage = true


[pagination]
  pagerSize = 10 # frontpage pagination

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/sheep5.jpg"
  SEOTitle = "Bonnie Luo"
  description = ""
  keyword = ""
  slogan = "Software Developer • Photographer • Podcaster • Improv Actor"
  upstreamAttribution = true

  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("

  # leancloud storage for page view counter
  page_view_counter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = true 
  email          = "youremail@gmail.com"
  linkedin       = "https://www.linkedin.com/in/yourlinkedinid"
  github         = "https://github.com/yourgithub"
  

  [[params.menus]]
  title =  "About"
  href =  "/about/"
  [[params.menus]]
  title =  "Tech"
  href =  "/tech/"
  [[params.menus]]
  title =  "Improv"
  href =  "/improv/"
  [[params.menus]]
  title =  "Podcast"
  href =  "/podcast/"
  [[params.menus]]
  title =  "Photos"
  href =  "/photos/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      